[package]
name = "rust_escape_room_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
crossterm_cursor = "0.4.0"
time = "0.3.30"
